USE CompLog;

ALTER TABLE activity
    MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    MODIFY COLUMN is_deleted TINYINT DEFAULT 0;

ALTER TABLE task
    MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    MODIFY COLUMN is_deleted TINYINT DEFAULT 0;

ALTER TABLE activity_task_relation
    MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    MODIFY COLUMN is_deleted TINYINT DEFAULT 0;

ALTER TABLE registration
    MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    MODIFY COLUMN is_deleted TINYINT DEFAULT 0;

ALTER TABLE user_task_record
    MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    MODIFY COLUMN is_deleted TINYINT DEFAULT 0;
